default: &default
  adapter: postgresql
  encoding: unicode
  username: byot
  pool: 5

development:
  <<: *default
  database: byot_development

test:
  <<: *default
  database: byot_test

production:
  <<: *default
  database: byot_production
  password: <%= ENV['DEMOCRARY_DATABASE_PASSWORD'] %>